### ISSUE TITLE
Invoking a process with sensitive command line argument - CWE 214

### ISSUE THREAD

**Issue by vigneshwaran-mohanasundaram** [Marcono1234/codeql-java-queries#15]
Hi Marcono,

I stumbled on your java codeql query packs and i found it very useful. I myself a newbie and trying to learn codeql to develop custom queries for my use-cases. I dont see we have standard query pack which covers the CWE#214 (Invoking a process with sensitive command line argument) . I have attached a simple java program on which am trying to match the value of argument "command" which is passed to runtime.exec() which contains sensitive command line parameter . 
Could you please assist me here if you have some time to spare ?

Thanks 
Vigneshwaran M

[sample.txt](https://github.com/Marcono1234/codeql-java-queries/files/11974326/sample.txt)

**Comment by vigneshwaran-mohanasundaram** [comment]
Forgot to attach my draft queries . But am struggling to match "-p" in my expr :s

/**
 * @name Potential Sensitive command-line argument constructed using string
 * @kind problem
 * @problem.severity warning
 * @id java/command-line-sensitive-argument
 * @tags security
 * @precision high
 * @security-severity 9.1
 */

 import java
 
 from MethodAccess mc, Expr arg , Variable var 
 where
   (mc.getMethod().getName().toLowerCase().matches("exec") or 
   mc.getMethod().getName().toLowerCase().matches("command") or 
   mc.getMethod().getName().toLowerCase().matches("start"))
   and
   var.getAnAccess() = mc.getArgument(0) and var.getAnAssignedValue() = arg and arg.toString().matches("%-p\\%")
 select mc, "Potential Sensitive command-line argument constructed using string: ", arg.toString()

**Comment by Marcono1234** [comment]
Maybe the queries [`java/concatenated-command-line`](https://github.com/github/codeql/blob/44f23bfa595dc930f65f6ca081ef0275382613dd/java/ql/src/Security/CWE/CWE-078/ExecUnescaped.ql) and [`java/command-line-injection`](https://github.com/github/codeql/blob/44f23bfa595dc930f65f6ca081ef0275382613dd/java/ql/src/Security/CWE/CWE-078/ExecTainted.ql) and the library file [`CommandLineQuery.qll`](https://github.com/github/codeql/blob/44f23bfa595dc930f65f6ca081ef0275382613dd/java/ql/lib/semmle/code/java/security/CommandLineQuery.qll) from the `github/codeql` repository can be helpful with this.

You would probably want to use `CommandInjectionSink` from `CommandLineQuery.qll` to handle detection of calls to `exec` and similar, then you don't have to determine this yourself.

To track flow from your `password` variable to the command execution you can use [taint tracking](https://codeql.github.com/docs/codeql-language-guides/analyzing-data-flow-in-java/#using-local-taint-tracking), this is more powerful than having to manually check variable assignments and reads. You have to use taint tracking instead of data flow tracking because the string concatenation (`... + " -p" + password + ...`) creates a new value and is therefore not considered data flow, see the [documentation for more details](https://codeql.github.com/docs/writing-codeql-queries/about-data-flow-analysis/#normal-data-flow-vs-taint-tracking).

For example your query could then look like this:
```codeql
/**
 * @kind problem
 */

import java
import semmle.code.java.dataflow.TaintTracking
import semmle.code.java.security.CommandLineQuery

from CompileTimeConstantExpr passwordOption, CommandInjectionSink sink
where
  passwordOption.getStringValue().matches("%-p%") and
  TaintTracking::localTaint(DataFlow::exprNode(passwordOption), sink)
select passwordOption, "This password option is used as command line argument $@", sink, "here"
```

Unless you explicitly want to check for the `-p` parameter as command line argument, you could instead use `SensitiveExpr` from [`SensitiveActions.qll`](https://github.com/github/codeql/blob/44f23bfa595dc930f65f6ca081ef0275382613dd/java/ql/lib/semmle/code/java/security/SensitiveActions.qll), that covers multiple names of variables or methods which might have a sensitive value, such as `password`, `passwd`, ...

```codeql
/**
 * @kind problem
 */

import java
import semmle.code.java.dataflow.TaintTracking
import semmle.code.java.security.CommandLineQuery
import semmle.code.java.security.SensitiveActions

from SensitiveExpr sensitiveExpr, CommandInjectionSink sink
where TaintTracking::localTaint(DataFlow::exprNode(sensitiveExpr), sink)
select sensitiveExpr, "This sensitive value is used as command line argument $@", sink, "here"
```

Also a tip regarding the code of your query, avoid checking the result of the `toString()` predicate, to my knowledge that is just a human readable string representation without any guaranteed format.

I hope that helps. Though I think in the future if you ask on https://github.com/github/codeql (possibly as Discussion) or on Stack Overflow you might get better or a greater variety of answers.

**Comment by vigneshwaran-mohanasundaram** [comment]
Hi Marcono,

Thanks much for your quick help and assistance and the explanation . Much grateful for your help and the tips

-Vignesh

**Comment by Marcono1234** [comment]
No problem, but if you are using this code for your own query [`SensitiveCommandlineArgument.ql`](https://github.com/vigneshwaran-mohanasundaram/codeql-shared/blob/main/Java-queries/SensitiveCommandlineArgument.ql) (especially if you copy the code without any changes), it would have been nice if you added a comment like the following to your code:
```
// Based on https://github.com/Marcono1234/codeql-java-queries/issues/15#issuecomment-1627404064
```

This also has the advantage that in case you or someone else wants to get more information about this again in the future, they can revisit my comment above.

No worries though, you can do with your code whatever you want to do regarding licensing; I won't raise any claims there or similar. It is just that writing that answer above also took me some time, so it would have been nice if that was recognized.

**Comment by vigneshwaran-mohanasundaram** [comment]
Rearranged my folder structure little bit 

https://github.com/vigneshwaran-mohanasundaram/codeql-shared/blob/main/java/ql/SensitiveCommandlineArgument.ql

Done :) . Thanks
